### ISSUE TITLE
Fails on `./gradlew -q updateAppSettings` using build tools 24.0.0

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-Scaffolding-Android#1]
Got the Build error with following stacktrace.

```
18:15:30.263 [ERROR] [org.gradle.BuildExceptionReporter] 
18:15:30.266 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:15:30.267 [ERROR] [org.gradle.BuildExceptionReporter] 
18:15:30.267 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
18:15:30.267 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
18:15:30.267 [ERROR] [org.gradle.BuildExceptionReporter] > failed to find Build Tools revision 24.0.0
18:15:30.268 [ERROR] [org.gradle.BuildExceptionReporter] 
18:15:30.269 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
18:15:30.269 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
18:15:30.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
18:15:30.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
18:15:30.271 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
18:15:30.271 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:510)
18:15:30.271 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
18:15:30.271 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Factories$1.create(Factories.java:22)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
18:15:30.272 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
18:15:30.273 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
18:15:30.273 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
18:15:30.273 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
18:15:30.274 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
18:15:30.274 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
18:15:30.274 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
18:15:30.275 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
18:15:30.275 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
18:15:30.275 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
18:15:30.275 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:15:30.276 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
18:15:30.276 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
18:15:30.276 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
18:15:30.276 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:48)
18:15:30.277 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
18:15:30.277 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
18:15:30.277 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
18:15:30.277 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
18:15:30.277 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
18:15:30.278 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
18:15:30.278 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
18:15:30.278 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
18:15:30.278 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.doAction(Main.java:33)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
18:15:30.279 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
18:15:30.280 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: failed to find Build Tools revision 24.0.0
18:15:30.281 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.sdk.DefaultSdkLoader.getTargetInfo(DefaultSdkLoader.java:87)
18:15:30.281 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:126)
18:15:30.281 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:680)
18:15:30.281 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:617)
18:15:30.281 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:572)
18:15:30.282 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:569)
18:15:30.282 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
18:15:30.282 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
18:15:30.282 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:568)
18:15:30.282 [ERROR] [org.gradle.BuildExceptionReporter]    at com.android.build.gradle.BasePlugin$10.execute(BasePlugin.java:565)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
18:15:30.283 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
18:15:30.284 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
18:15:30.284 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
18:15:30.284 [ERROR] [org.gradle.BuildExceptionReporter]    ... 44 more
18:15:30.284 [ERROR] [org.gradle.BuildExceptionReporter] 
```

**Comment by ben181231** [comment]
I have some updates (Commit 943d7a827ecf57455064f992f9c56719dd921e91) so that the script will find a proper build tools version >= 24.0.0. 

@rickmak Can you try it again? Remember to clear the gradle cache in `$HOME/.gradle`.
